# Generated by Django 6.1 on 2026-08-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional emoji fallback if no image is uploaded, e.g. 👗', max_length=10),
        ),
    ]
